org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
unityStreamingAssets=.unity3d, .ress, .resource, .obb, .bundle, .unityexp

unity.androidSdkPath=C\:/Users/vasan/AppData/Local/Android/Sdk
unity.androidNdkPath=C\:/Program Files/Unity/Hub/Editor/6000.3.15f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
